### ISSUE TITLE
precompiled ts artifacts + gitignore?

### ISSUE THREAD

**Issue by njs50** [mgechev/angular-seed#1453]
I ran into a weird issue with one of our dev's where they had precompiled ts in their /tools dir, where there is a gitignore that prevents them from showing up in `git status`. i.e `tools/config/project.ts` -> `tools/config/project.ts/project.js+project.js.map`

during the build it was using those old artifacts without recompiling them and causing issues (is this a tsconfig issue?).

i don't see any precompiling happening in the current version, so maybe that .gitignore should be removed so at least the old files show up?

**Comment by lifaon74** [comment]
It's normal => https://github.com/mgechev/angular-seed/wiki/Speed-up-the-build-on-Windows
Files are pre-compiled. You'll need to execute `tsc --project tsconfig.json` everytime you change something into tools/. Personnaly I recommand not to precompile, avoiding to do it manually.

**Comment by njs50** [comment]
this happened to a developer's build who doesn't ever touch the angular code on osx. not sure how those files would have been created.

seems like the sort of thing the clean should be removing before a prod.build if we are going to be ignoring them

**Comment by mgechev** [comment]
If you run `tsc` in the root of the seed, all the TypeScript files in `tools` will be compiled to JavaScript. As @lifaon74 mentioned, in some cases this could be intentional because of the slow TypeScript compilation in Windows which slows down the entire build process.

It is also possible any editor or other tool that your coworker is using to have invoked the TypeScript compiler. If you're **sure** that you don't have any important JavaScript or sourcemaps in `tools`, you can run:

```shell
find . -type f -name '*.js.map' -delete && find . -type f -name '*.js' -delete
```

**Comment by njs50** [comment]
it seems like a bad that a prod build is using old artifacts, and that none of the clean tasks will clear those out. I would expect a prod build to not use any existing artifacts, and be 100% repeatable.

Given the tendency of ide's to trick users into compiling their ts this seems like something that could potentially be quite confusing.

**Comment by mgechev** [comment]
Yes, it is not recommended but brings a serious performance boost so it is the "last step" that you can take in order to speed-up the Windows build process.

**Comment by njs50** [comment]
i don't think the speed matters for a prod build. maybe we need a task in the npm `build.prod` that checks to see if the compiled ts exists and then recompiles it if it does.

**Comment by mgechev** [comment]
It brings improvement for both - development and production. On Windows it used to get really slow until your build gets started. 

Yes, having such task makes sense. This can be part of `gulpfile.ts` which verifies if everything is up-to-date every time.

**Comment by njs50** [comment]
ah, there are already two tasks to clear those files 'clear.files' and 'clean.tools'. It would need to be run prior to the `gulp build.prod` command tho, so that those files are cleaned.

**Comment by lifaon74** [comment]
Yes... but if we check all projects ts files before building and re-compiling them, will we not loose all (and uniq) advantages of precompiling ts files (for speed) ?

Your issue seems more a be a developer "error" instead of a code problem...

>i don't think the speed matters for a prod build. maybe we need a task in the npm build.prod that checks to see if the compiled ts exists and then recompiles it if it does.

Maybe not for your projects, but never forget that thousands of users use ng2-seed and some probably need this speed boost.

**Comment by njs50** [comment]
developers shouldn't be doing prod builds on a regular basis. people who are doing prod builds should know with 100% certainty that they are running the code that they have checked out.
