### ISSUE TITLE
How to use AOT

### ISSUE THREAD

**Issue by AAAnderson7301** [mgechev/angular-seed#1466]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

I have searched through the open/closed issues and am stumped on how to use AOT. I have built the seed using npm run build.prod.exp and when I look in dist/tmp I see the generated factories but when I load up index.html in the browser I get the following screen
 ``` Loading...    <% if (ENV === 'dev') { %> <% } %>    <% if (ENV === 'dev') { %> <% } %>  ```

Can someone add to the docs how to deploy/load an AOT project.

**Comment by mgechev** [comment]
All you need to do is to run `npm run build.prod.exp` ("exp" comes from "experimental").

Once the project is built successfully all the files are in **`dist/prod`**. The factories are bundled with the rest of the code. Most likely you're trying to do something with the `tmp` directory which contains only temporary files and they are not intended for usage by the end user but only as part of the build process.

In order to deploy the application you need to upload `dist/prod` to your static file server.
