### ISSUE TITLE
Test failing on external dependency

### ISSUE THREAD

**Issue by zwolejo** [mgechev/angular-seed#1472]
Hello, I've migrated project to newest version and when i am trying to run my tests I am getting:

`    404: /myaviva-web/node_modules/moment/moment.js`

I've added moment by adding to project.config.ts:

```
this.SYSTEM_CONFIG_DEV.paths['moment'] = `${this.APP_BASE}node_modules/moment/moment`;
    this.SYSTEM_BUILDER_CONFIG.packages['moment'] = {
      main: 'moment.js', defaultExtension: 'js'
    };
```

I also tried to include moment in karma.conf  with:

`{ pattern: 'node_modules/moment/**/*.js', included: false, watched: false },`

**Comment by mgechev** [comment]
Most likely you took a look at how we configured karma to load Angular and you're doing the same for moment, so you're in the right direction.

Your configuration seems good to me but I suppose the request should be to `/base/node_modules/moment/moment.js` instead of `/myaviva-web/node_modules/moment/moment.js`. Have you done any changes in `karma.config.js`?

**Comment by zwolejo** [comment]
I found out there is base path in test-config.js
`baseURL: '/base/'`
while My application uses base href in seed.config.ts as 
`APP_BASE = argv['base'] || '/myaviva-web/';`

So i decided to revert changes and use base href 
`"/"`
But i still get messages like:
`404: /node_modules/moment/package.json //why for external he not search in base`
I dont know what is this "base". I dont see any base folder in dist.

my component imports moment as:
import * as moment_ from 'moment';

**Comment by mgechev** [comment]
Yes, there is no base directory. Please, take a look at karma.config and test-main.js, and see what the configuration for the seed is in order to get a better understanding how everything works together. 

For support requests I'd recommend you to use gitter or stackoverflow. The issue tracker is reserved for issues and feature requests only.
