### ISSUE TITLE
lodash doesn't compile to production #1463

### ISSUE THREAD

**Issue by grauschnabel** [mgechev/angular-seed#1498]
this is a reopen of #1463 , because I cannot open it there, and noone is answering...

I don't use lodash by myself, but thought angular2-seed would use it. Removing lodash by npm uninstall lodash (its not in the package.json here) also leads to an error:

[11:38:45] 'css-lint' errored after 296 ms
[11:38:45] Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/martin/Projects/lf/client/node_modules/postcss-reporter/lib/reporter.js:2:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[11:38:45] 'build.prod' errored after 8.89 s
[11:38:45] Error in plugin 'run-sequence(css-lint)'
Message:
    Cannot find module 'lodash'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/martin/Projects/lf/client/node_modules/postcss-reporter/lib/reporter.js:2:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by mgechev** [comment]
Most likely there's something missing in your configuration, the solution in https://github.com/mgechev/angular-seed/issues/1463 works perfectly for me. Take a look at [this commit](https://github.com/mgechev/angular-seed/commit/955e04b3de55c7d06118617a1d79598667c7f073).

**Comment by JackMorrissey** [comment]
#1463 worked for me.

```ts
import { startCase } from 'lodash/string';
```

**Comment by CNorris724** [comment]
@grauschnabel Did you ever solve this?

**Comment by rramo012** [comment]
@grauschnabel I had the same issue as your original post.

` 
case 0: return func.call(thisArg);
SyntaxError: Unexpected token .
`

It turned out being an issue in the compile process of a template. More specifically I had "${{priceVar..." in one of html files. The dollar sign seemed to throw a wrench in things.

I was able to debug it by logging the files in: node_modules/gulp-template/index.js:20:14 

Hope that helps anyone with a similar issue.

**Comment by CNorris724** [comment]
This is exactly what my problem was too..  Thanks @rramo012

**Comment by alexlukin-softgrad** [comment]
@mgechev I've taken a look at the ['lodash' branch](https://github.com/mgechev/angular-seed/tree/lodash) and it no longer works for me... Can you please update this brunch on top of the current master?
There are many questions in gitter about how to make lodash work, but I couldn't find a working solution and have no ideas how to make lodash work in angular-seed.

**Comment by alexlukin-softgrad** [comment]
Sorry for uneasiness. I've figured out with it. To add lodash to my angular-seed project I've done the following:
1. `npm install lodash --save`
2. `npm install "@types/lodash --save-dev`
3. Add this section to `additionalPackages` array in `project.config.ts`

```
let additionalPackages: ExtendPackages[] = [
      ...
      {
        name: 'lodash',
        path: `node_modules/lodash/lodash.js`
      }
];
```
`// {src: 'lodash/lodash.min.js', inject: 'libs'},` still remain commented in `this.NPM_DEPENDENCIES`

4. Make this import in my component.ts file
```
import * as lodash from 'lodash';
declare var _: any;
_ = lodash;
```

**Comment by dcarabott** [comment]
I'm still having this issue.

As @JackMorrissey instructed, I've tried to debug the files and the culprit seems to be the '_' (lodash). 
 I've tried all the mentioned above to no avail. 

Getting `case 0: return func.call(thisArg);` when starting `transpile.bundles.rollup.aot`

Tried adding lodash through the following: 

`
        this.SYSTEM_CONFIG_DEV.paths['lodash'] = `${this.APP_BASE}node_modules/lodash/`;
        this.SYSTEM_BUILDER_CONFIG.packages['lodash'] = { main: 'lodash.js', defaultExtension: 'js' };`

or

`        let additionalPackages: ExtendPackages[] = [
            {
                name: 'lodash',
                path: `node_modules/lodash/lodash.js`
            }
        ];`

  or in seed.config.ts

`
      'lodash': 'node_modules/lodash/lodash.js',`

Any insights?

**Comment by coding2012** [comment]
I was able to fix this issue by avoiding the ${ sequence in my templates. If you are using $ for dollar sign, then you can use the HTML entity &#36; instead.

**Comment by Flood** [comment]
I am experiencing this issue as well. I do not have any ${ sequence in my templates.

Using latest seed with:
```
"lodash": "^4.17.4",
"@types/lodash": "^4.14.37",
```

It fails only on AoT build.

Using "import * as _ from 'lodash';"

**Comment by Flood** [comment]
@alexlukin-softgrad Do you have to declare lodash like that?

```
import * as lodash from 'lodash';
declare var _: any;
_ = lodash;
```

**Comment by JackMorrissey** [comment]
Hey @Flood, I just started over with the seed a few days ago and got lodash going. Here's my commit -

https://github.com/JackMorrissey/angular-seed/commit/382af0e2c35a4030e8c45c38bfa8ec42c25af529

Hopefully that gives you something to compare to.

**Comment by Flood** [comment]
Thanks @JackMorrissey, is AoT build working for you? Seems like we have the same setup. Maybe I have something similar to the ${ sequence in my templates then.

**Comment by JackMorrissey** [comment]
To be honest, I haven't tried that yet. I'll touch back once I get a chance to play with it a bit more.

**Comment by drosi94** [comment]
I have the same problem with aot rollup, aot complies succesfully

**Comment by fvandangeon** [comment]
I don't know if it's relevant in your context but I noticed that if you compile the Typescript with the "removeComments : false" option the aot rollup failed with this lodash error.
If you force this option to true , the issue disappear and rollup aot works perfectly.
... I don't investigate why but you can give a try ...

**Comment by Flood** [comment]
@fvandangeon "removeComments:true" is default in the seed. Or where should I change?

**Comment by fvandangeon** [comment]
My rollup aot was working perfectly and I've put "removeComments:false" in the tsconfig file because I want to use /* istanbul ignore if */  features for coverage. Then I noticed that the rollup aot build failed with the lodash error (although i'm not referencing lodash directly in my package.json).

So  I've remove the option in the tsconfig file and add it directly in the calls of makeTsproject in task setting it to true for prod tasks or false for dev tasks. like this : 
let tsProject = makeTsProject({ removeComments: true });

No more lodash error in rollup aot (and istanbul ignores working fine :p for coverage).

Hope this helps ...

**Comment by Flood** [comment]
This did not help for me. In which file did you change?

I've changed in `transpile.bundles.rollup.aot.ts`, do I have to add "removeComments: true" in more places?

**Comment by fvandangeon** [comment]
sorry to hear that, maybe it's another issue ...
I've add "removeComments: true" into all prod tasks :  
`transpile.bundles.rollup.aot.ts` 
`build.js.prod.ts` 
`build.js.prod.rollup.aot.ts`
`build.js.prod.aot.ts`

**Comment by Flood** [comment]
Just tried adding to all four and it did not help :/

**Comment by timbilt** [comment]
This line
`.pipe(plugins.template(new TemplateLocalsBuilder().build(), {interpolate: /<%=([\s\S]+?)%>/g}))`
in build.js.prod.rollup.aot.ts was the cause of the problem for me.

Thanks @rramo012

**Comment by Flood** [comment]
@timbilt Did you remove it or what did you change?

**Comment by timbilt** [comment]
@Flood, I just commented it for now.   I'll take a look at it soon to figure out a solution.

**Comment by RoxKilly** [comment]
@timbilt , @Flood you don't need to comment out the whole line (that will prevent `gulp-template` from parsing the files). Instead, just remove the `interpolate` argument.  In file `tools/tasks/seed/build.js.prod.rollup.aot.ts`, change the line (32):
```
.pipe(plugins.template(new TemplateLocalsBuilder().build(), {interpolate: /<%=([\s\S]+?)%>/g}))
```
to...
```
.pipe(plugins.template(new TemplateLocalsBuilder().build()))
```
This should fix the error without actually changing the build process, since that argument was set to the default value anyway.

**Comment by dcarabott** [comment]
@Flood Did you manage to solve it after all?

**Comment by sclander** [comment]
Thank you @rramo012 !!

**Comment by hakimovic** [comment]
Hi I just had the issue and I fixed it by removing all `<%=` from my files, I ended up doing
```
let escapedStr = '<';
escapedStr += '%='
```
and interpolate that in my html with `{{ escapedStr }}`

What another could do is escaping these ERB chasr with the defined escape character in `tools/config/seed.config.ts`  in the `TEMPLATE_CONFIG` object something like `escapedStr = '<%- '<%= some values >' %>'`

Another solution that I imagine is replacing these chars in the TEMPLATE_CONFIG object and everywhere they are used...

Hope that helps!
