### ISSUE TITLE
build.bundles.app Error - Loader looking in node_modules/ for files in src/client/*

### ISSUE THREAD

**Issue by nrbbrg-at** [mgechev/angular-seed#1503]
**Steps to reproduce and a minimal demo of the problem**

Start in the project root.

First, create a utilities file:
mkdir src/client/utilities && echo "export class Blah {}" > src/client/utilities/blah.ts

Then, in main.ts:
import { Blah } from '../utilities/blah';
let b: Blah = new Blah();

Now, npm run build.prod:

[13:27:19] 'build.bundles.app' errored after 733 ms
[13:27:19] Error on fetch for dist/tmp/utilities/blah.js at file:///Users/erich/opt/angular2-seed/node_modules/dist/tmp/utilities/blah.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/Users/erich/opt/angular2-seed/node_modules/dist/tmp/utilities/blah.js'
    at Error (native)

**Current behavior**

Loader is looking in node_modules/dist/tmp when it should be looking in dist/tmp

**Expected/desired behavior**

It worked before, and the docs don't say files have to be under app/*, so it should preserve the existing behavior.

**Other information**

**Comment by mgechev** [comment]
`utilities` should be in `app`, otherwise you need to add entry in `SYSTEM_BUILDER_CONFIG` similar to the [one here](https://github.com/mgechev/angular-seed/commit/0c972d671c4337d361f56fa3684dac4601aaedbf#diff-3d695f3c2a28f15f1129d3a122b806d5R396). The directories on the level of the `app` directory are considered separate applications. One of the features of the seed is that you can run multiple applications with shared codebase.
