### ISSUE TITLE
Slow load time on Android

### ISSUE THREAD

**Issue by Allsimon** [mgechev/angular-seed#1549]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

App is built with `npm run build.prod` and app.js weight around 900kb. The app load really fast on desktop: around 200ms, but is really slow on mobile (around 9 sec on a Nexus 7 2013). 90% of the time is spent evaluating app.js

**Expected behavior**
Load a wee bit faster :)

**Minimal reproduction of the problem with instructions**
Initial support for Google Closure Compiler:
`git checkout e8105f1 && npm run build.prod && cd dist/prod && serve`  => 3.5s
On latest lazy:
`git checkout f7ca77a && npm run build.prod && cd dist/prod && serve`  => 5.5s
On latest master:
`git checkout 4b4570 && npm run build.prod && cd dist/prod && serve`  => 7s

It seems that there is a regression (200%) in load time (since Closure Compiler was dropped ?) I'm gonna try to bisect this.

Do you have any idea how I could improve this loading time right now ?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

In order to follow the improvements in the production build take a look at this issue https://github.com/mgechev/angular-seed/issues/864.
