### ISSUE TITLE
Time to change to Webpack?

### ISSUE THREAD

**Issue by webia1** [mgechev/angular-seed#1552]
What do you think?

**Comment by irsick** [comment]
I've chose this boilerplate repo because it's using systemjs + gulp which are broadly used in our corporate environments. Switching to webpack defeats the purpose of having an alternative to https://github.com/angular/angular-cli which is already using webpack. 

Why don't you try angular-cli instead?

**Comment by webia1** [comment]
Apropos gulp, why not forego it completely? Nmp alone would be a better choice,..

Angular-cli is a terrible copy of ember-cli, the only positive thing there is the idea,..

**Comment by mgechev** [comment]
Hey @webia1! I'm not sure about the future of gulp so most likely there's going to be a change at some point and we should try to make the transition as painless as possible.

I don't think webpack is the best candidate. Although it's declarative and has minimalistic configuration, I feel it lacks flexibility when adding new features. It took a while an AoT compilation plugin to be developed, while we had AoT support in the seed right after NgModules were introduced. I prefer to have the independence and flexibility of simple pure JavaScript/TypeScript tasks instead of having a bunch of custom webpack plugins.

npm scripts are nice too but I believe it'll become a real nightmare to manage all the different tasks that we currently have by using them.

This doesn't have to be another "npm scripts vs webpack vs gulp", maybe webpack will be the next step, maybe gulp 4 will be released, maybe we'll go in another direction. I believe we're good for now. We can use whatever bundler we want (rollup, system builder...well even webpack 2...), we can apply whatever bundling strategy we prefer, we have the flexibility to adapt to the nest changes in the AoT compiler without being blocked by third party plugins.

So lets wait a bit and see what the best solution will be :-).

**Comment by jerryorta-dev** [comment]
In case anyone comes across this issue searching for WebPack...

Like I did with the JSPM version of this project, I encourage anyone to give WebPack a full test drive based on this project just to see the full impact analysis.  And to give people an option.

**Comment by Shyam-Chen** [comment]
change to Rollup...
