### ISSUE TITLE
TS2307: Cannot find module './app.module.ngfactory'.

### ISSUE THREAD

**Issue by webia1** [mgechev/angular-seed#1582]
I'm submitting a possible bug report or a kind of configuration error:

```
.....app\src\client\app\main-prod.ts
Error:(8, 36) TS2307: Cannot find module './app.module.ngfactory'.
```

the newest version of the seed (today), windows, tsc v2.0.3

**Comment by webia1** [comment]
these are the next messages:

```
config/seed.config.ts[3, 13]: Unused import: 'util'
utils/seed/tasks_tools.ts[6, 13]: Unused import: 'tildify'
```

**Comment by webia1** [comment]
my first intention was, it would be created maybe on the fly in the production mode but I've found a similar problem here: https://github.com/mgechev/angular-seed/issues/1338 

solution: just ignoring it for a while,..

**Comment by omerfarukyilmaz** [comment]
(8, 36) Cannot find module './app.module.ngfactory'.

I get this as well but it causes no problems.

> config/seed.config.ts[3, 13]: Unused import: 'util'

should be fixed with https://github.com/mgechev/angular-seed/commit/ea7e398b710d71a8becf8ada4854dfc6661ac0b7#diff-3d695f3c2a28f15f1129d3a122b806d5L3

> utils/seed/tasks_tools.ts[6, 13]: Unused import: 'tildify'

check that you have the latest `tasks_tools.ts`. tildify should be used in [tasks_tools.ts:54](https://github.com/mgechev/angular-seed/blob/master/tools/utils/seed/tasks_tools.ts#L54)

> solution: ignoring it for a while,..

Yes, just ignoring it is fine.

**Comment by mgechev** [comment]
`main-prod.ts` is used for AoT compilation. It references `app.module.ngfactory.ts` which doesn't exist until we run `ngc` so by default we're ignoring `main-prod.ts` and `app.module.ngfactory.ts` unless we're in a final phase of AoT.

Most likely you did something which caused `tsc` to compile `main-prod.ts` which seems incorrect. I'd recommend you to run a diff between the `tools` directory in master and the one that you have.
