### ISSUE TITLE
Issues in running karma

### ISSUE THREAD

**Issue by kapoorruchi** [mgechev/angular-seed#1616]
**I'm submitting an issue with running karma test case. We are using external library angular2localization and on running test using "npm test"  , we are getting below issue. I have searched similar issue in angular2 seed, but could not find it anywhere.

09 11 2016 12:31:12.195:WARN [web-server]: 404: /base/node_modules/angular2localization/bundles/angular2localization.umd.min.js
Chrome 54.0.2840 (Windows 7 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/angular2localization/bundles/angular2localization.umd.min.js
        Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/angular2localization/bundles/angular2localization.umd.min.js
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:647:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:236:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:136:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:304:33)
        Error loading http://localhost:9876/base/node_modules/angular2localization/bundles/angular2localization.umd.min.js as "angular2localization" from http://localhost:9876/base/dist/dev/app/app.component.js'

**Current behavior**
On running npm test, above issue is coming, and tests is failed.

**Expected behavior**
There should not be such issue and test case must run.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
 Operating system- Windows 7, IDE - Visual studio code, package manager - npm, HTTP server
npm --version = 3.10.8

* **Angular Seed Version:
"name": "angular2-seed",
  "version": "0.0.0"

* **Node:** `node --version` =v6.8.0

**Comment by jesperronn** [comment]
Please, could you show how you modified files in order to follow the wiki page https://github.com/mgechev/angular-seed/wiki/Add-external-dependency

* Is it only when running tests, that the dependency cannot be found. 
* Can you run `npm start` without errors in the browser console? 
* What about production mode: Can you run `npm run serve.prod` without errors in the browser console?

**Comment by sangecz** [comment]
I have similar issue but with ng2-webstorage, i read the wiki but those two steps required for testing didn't work.

**Comment by samuelfernandez** [comment]
Try to add it to karma.conf.js. Open this file, and in `files` array add a line like this:

`{ pattern: 'node_modules/angular2localization/bundles/angular2localization.umd.min.js', included: false, watched: false },`

If not try with something like:

`{ pattern: 'node_modules/angular2localization/**/*.js', included: false, watched: false },`

Hope it helps!

**Comment by sangecz** [comment]
I already did with ng2-translate and ng2-webstorage and included it also in test-config.js just like described in wiki, same error

**Comment by sangecz** [comment]
I get the files loaded in browser by inserting this  to karma.con, files:
`      {pattern: 'node_modules/angular-2-local-storage/dist/angular-2-local-storage.js', included: true, watched: false}`
however i got this error:

```
.... ERROR
  Uncaught ReferenceError: require is not defined
  at node_modules/angular-2-local-storage/dist/angular-2-local-storage.js:2

Finished in 0.497 secs / 0 secs
.....
```
I think that it is because angular-2-local-storage is a commonjs module and not a systemjs one.

how could I setup it correctlly? 

I'm able to run npm start after adding `'angular-2-local-storage': 'node_modules/angular-2-local-storage/dist/angular-2-local-storage.js'` to SYSTEM_CONFIG_DEV.paths, doing the same but for test-config.js does not work...

**Comment by mgechev** [comment]
[Here](https://github.com/mgechev/angular-seed/issues/1663#issuecomment-262954490) @vyakymenko listed the steps required for including a dependency in `karma.config.js`.
