### ISSUE TITLE
Bundling css file does not include compiled scss files in production mode 

### ISSUE THREAD

**Issue by cuongdn** [mgechev/angular-seed#1660]
[x] bug report => search github for a similar issue or PR before submitting

**Current behavior**
I override some config in project.config.ts as follows
`  this.ENABLE_SCSS = true;`

`  this.APP_ASSETS = [`
      `{ src: ``${this.ASSETS_SRC}/layouts/layout/css/layout.min.css``, inject: true, vendor: false },`
      `{ src: ``${this.ASSETS_SRC}/layouts/layout/css/themes/darkblue.min.css``, inject: true, vendor: false },`
      `{ src: ``${this.ASSETS_SRC}/pages/css/login.min.css``, inject: true, vendor: false },`
     `{ src: ``${this.ASSETS_SRC}/layouts/layout/css/custom.css``, inject: true, vendor: false },`

I have a file `custom.scss`. When building project, the custom.css was generated (in both folders `dist/dev `and `dist/tmp`). But bundling file `main.css` in `dist/prod` does not include compiled scss file. It only includes 3 first files. Everything displays OK in development but not in production.

**Expected behavior**
All injected css files must be included in bundling file `main.css` in production

**Comment by pratheekhegde** [comment]
Instead of specifying your css in the project configs, rename all your css files to scss and import it in `css/main.scss`.

https://github.com/mgechev/angular-seed/wiki/Working-with-SASS

I tried your method a while ago, it was failing for me too.

**Comment by kobvel** [comment]
Any workarounds of this issue?

**Comment by bonaparte89** [comment]
I'm struggling around with the same issue. Is there an idea or plan when this is going to be fixed?

**Comment by lifaon74** [comment]
In fact you're doing it wrong. Take a look at : https://github.com/mgechev/angular-seed/wiki/Working-with-SASS

- You basically need 2 folders: **css** where the scss files will be compiled and copied to dist, and **scss** , a folder which will not be compiled and copied.
- Create a main.scss into the css folder and import all the scss/css you need. You should not do it into project.config.ts because it wont bundle and minimize your css files. => The purpose is to have only 1 end file (main.css) which will contain all you style, avoiding code duplication and fasten the build.
