### ISSUE TITLE
Question - Angular CLI or Angular Seed

### ISSUE THREAD

**Issue by Martin-Andersen** [mgechev/angular-seed#1661]
First this project seems very mature compared to Angular CLI.
My question is, why to big CLI projects? and will you continue to developer "Seed" as "CLI" gets more mature?

**Comment by TheDonDope** [comment]
Hi @Martin-Andersen,
thank you for this interesting issue!
I'll tell you a bit about my personal stance towards this: I started to develop Angular 2 applications in March 2016, when Angular was in Late Alpha, Early Beta. Angular-CLI was not around back then so i looked for a seed project and found this one here. It gave me a really good headstart, since the whole build infrastructure was set up, ready to use. As i continued to develop with the seed, i started to contribute to it, and continue to do so to this day. 

However, recently in a new project of mine, i am experimenting with angular-cli. I started developing web applications with Ruby on Rails and found the whole cli integration that came with it fantastic for developer productivity. Like, for example initializing a basic project structure, generating code for components etc. Even though angular-cli is younger than this seed project i feel it is quite usable so far. It reminds me a bit of the cli that ships with rails. 

Regarding angular-cli though you might want to check with those news on which direction it might move in the future: [Angular Weekly Meeting Notes, November 14th](https://docs.google.com/document/d/1rC5dz7AkCZP813daT_bccbS-20OLmXgBVi50CSKx148/pub).

Cheers

Dope

**Comment by Shyam-Chen** [comment]
This project is migrating from SystemJS to Rollup for Tree-shaking support.

**Comment by mgechev** [comment]
@Martin-Andersen yes, most likely we'll keep working on the seed even after the CLI gets mature. There are a few benefits of using a seed project (really, any seed project, not this specific one). The one which attracts me most is that I'm not tightly coupled with a tool, instead I'm just getting a starting point.

There are a few features which are specific to this project and make life easier:

- You can keep the project up-to-date with upstream relatively easy. Of course, if you're using the project only as a starting point you don't have to, but if you want to, you can.
- The build is quite flexible so as part of it you can plug whatever you want to. For instance, as part of the build pipeline of my project I'm bundling several modules for lazy loading and pushing them to S3. I also have SVG sprite generation and much more.
- The seed supports multiple applications with shared codebase.

@Shyam-Chen is correct that at some point we'll switch to Rollup or Google Closure Compiler. That's an incremental improvement that we're going to make in order to improve the build's efficiency.

On the other hand, the CLI is great and it's going to get even better. I'm staying in touch with the CLI guys and working on tools for static code analysis with them.

What should you choose? I guess it's mostly a matter of a personal preference.

**Comment by Jimhub214** [comment]
please also see https://coderanch.com/t/675948/Angular-Development-TypeScript-Angular-CLI
