### ISSUE TITLE
Docker production build does not work macos

### ISSUE THREAD

**Issue by consigliory** [mgechev/angular-seed#1668]
it throw error /bin/bash: /etc/nginx/conf.d/angular-seed.template: No such file or directory

**Comment by mgechev** [comment]
@TheDonDope would you take a look at this?

**Comment by TheDonDope** [comment]
Hi @consigliory, can you give some more details about what exactly you started?

From your issue title i presume you try to do an production docker build on macOS.

Did you take the follwing steps like described in the documentation (https://github.com/mgechev/angular-seed#dockerization) ?

```bash
$ docker-compose -f docker-compose.production.yml build
$ docker-compose -f docker-compose.production.yml up angular-seed   # Wait until this container has finished building, as the nginx container is dependent on the production build artifacts
$ docker-compose -f docker-compose.production.yml up -d angular-seed-nginx  # Start the nginx container in detached mode
```

**Comment by consigliory** [comment]
I am using macOs sierra. I did follow steps running this commands in sequence but for some reason angular-seed-nginx container fails to start.
previously I was able to make very simple dockerfile which made image and starts app npm run build.prod but with this update this image is also fails and complains about gulp is not available. So unfortunatly I am kinda in broken situation now. I definatly has to learn more about docker but for now I had high hope that your stuff can do it best in class. Thanks a lot for your project it is really awesome and usefull project

**Comment by consigliory** [comment]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN Meduza@1.0.0 No license field.

**Comment by TheDonDope** [comment]
Hey @consigliory:

try the following:

```bash
$ rm -rf dist node_modules tmp
$ docker-compose -f docker.compose-production.yml build
$ docker-compose -f docker-compose-production up angular-seed
```

*Wait until the last command finished. This will internally run an `$npm run build.prod` inside a container. The `dist/` directory inside the container is linked to the `dist/` directory on your local machine. Therefore you need to wait until this container has finished building*

Next, boot up the Nginx container (which copies the built files from `dist/` into its container and serve the application:

```bash
$ docker-compose -f docker-compose.production.yml up -d angular-seed-nginx
```

*Note:*

This implementation is necessary, because even though `docker-copose` file reference v2 supports container dependencies via `depends_on:` it is not enough to link the two cotainers (The `npm run build.prod` one, and the Nginx one), because `depends_on:` only guarantees to start the node *before* the nginx container, but *not* to wait for the node container to finish building. (There are workarounds with `wait_for_it` scripts, but i haven't gone through the hassle to look in detail at it. Therefore i chose the "simpler" workaround that requires you to actually wait yourself for the node container to finish building and then start the Nginx container. (If there was not the `depends_on:` issue, a simple `$ docker-compose -f docker-compose.production.yml up` would be sufficient)

Can you please try again? Ping if you need further help
