### ISSUE TITLE
Feature request: Let community donate

### ISSUE THREAD

**Issue by webia1** [mgechev/angular-seed#1676]
That's a great job here, I daily use the seed and get quick answers for my problems, would donate a small sum.  I think many people would think the same. 

Thank you!

**Comment by mgechev** [comment]
Hey @webia1, thanks for the suggestion I'm really happy that the seed is useful for you!

The project became what it is because of [all the contributors](https://github.com/mgechev/angular-seed#contributors) who helped to make it that awesome. As a donation I'd suggest help with the resolution of any of the pending issues/improvement of the wiki.

I'll create a new tag in the issue tracker where we can mark issues which are good starting points for contribution so anyone who is willing to help can do so.
