### ISSUE TITLE
How to add tsd files to the project

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular-seed#1685]
Hi, first of all, sorry, I know that this is not the place to post doubts. But I search a lot at this issues project, wiki, I tried putting my doubt at gitter, searching again at google and nothing.
I tried run all this commands:
`npm install --save @types/sweetalert`
`npm install --save @types/jquery`
`typings install jquery --ambiente --save`
I need to put the reference at my .ts file like:
`/// <reference path="../../../../../typings/jquery/jquery.d.ts" />`

How is the correct way to use tsd files?

Thank you and sorry for any inconvenience

**Comment by mgechev** [comment]
Since you're using `@types` you don't need typings. The process is:

```shell
npm i @types/immutable --save-dev
```

Also, will not recommend you using jQuery. There are many reasons for this but maybe the most obvious one is that your code will not be portable so it won't work in WebWorkers. 

Also, with jQuery you may also have [typing collision with Protractor](https://github.com/mgechev/angular-seed/issues?q=is%3Aissue+Protractor+jQuery+is%3Aclosed).

**Comment by gustavolira** [comment]
@mgechev Thank you very much for your answer.
jQuery was just an example. Just the last question, I need to put the reference `/// <reference path="../../../../../typings/jquery/jquery.d.ts" />` at every .ts file that I want to use?

**Comment by mgechev** [comment]
No, you don't need an explicit reference.
