### ISSUE TITLE
Extraction failed i18n

### ISSUE THREAD

**Issue by 093lus** [mgechev/angular-seed#1700]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

TypeError: compiler.analyzeAndValidateNgModules is not a function
when running "./node_modules/.bin/ng-xi18n"

**Expected behavior**

Cant generate messages.xlf file
**Minimal reproduction of the problem with instructions**

I have tried on my Project, also I have downloded a project from github, have deleted that file and run the command. The same TypeError
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 8, Visual Studio, Webstorm, npm,
* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =
v6.9.1

**Comment by mgechev** [comment]
It seems someone met the same [problem here](http://stackoverflow.com/questions/41034295/node-modules-bin-ng-xi18n-not-genareting-file-named-messages-xlf).

You can take a look at the Angular issue tracker and if such issue doesn't exist report it there. Since following the cookbook's recommendations doesn't work it seems like an issue related to Angular/the documentation, not the seed.

**Comment by Doehl** [comment]
Did you ever found a solution to the problem, because I have the same problem?

**Comment by 093lus** [comment]
Hi, actually I have changed my solution. But I assume, if you will creat
your project with angular cli it must work.

2017-01-03 13:00 GMT+04:00 Mathias Døhl <notifications@github.com>:
