### ISSUE TITLE
barrels removed from official ng2 style guide but not in the seed

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular-seed#1744]
I was browsing the official [Angular 2 style guide](https://angular.io/docs/ts/latest/guide/style-guide.html) and I noticed that they removed any mentions of barrels.  I know that they previously had it in there but looks like it is gone now.  However, it looks like the seed still uses barrels.  

Since I know that @mgechev contributed to the style guide, I wanted to ask the following 2 questions:

- What was the reason that barrels were removed from the style guide

- Should we continue to use barrels in our projects if it is not listed in the guide?

**Comment by mgechev** [comment]
Barrels are not considered bad practice. In the same time they are not as essential for the structure of the application as before, so that's why they are not listed in the style guide.

Although barrels are no longer listed in the Angular style guide, this doesn't mean that we should not use them in our projects. I still find them quite handy in cases I want to apply an encapsulation on module level, or I build a hierarchy of exports for shortening the imports' paths.

I dropped them from the seed since I don't think they are contributing to the overall structure here.
