### ISSUE TITLE
build.prod.rollup.aot ReferenceError: require is not defined

### ISSUE THREAD

**Issue by 13812453806** [mgechev/angular-seed#1829]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
npm run build.prod.rollup.aot then deploy to server
I get ReferenceError: require is not defined by use require('../../../js/protobufjs/ComBase.js')
to require third js

**Expected behavior**
same code build.prod.aot success, no any error

**Minimal reproduction of the problem with instructions**
require any third js , then npm run build.prod.rollup.aot then deploy to server

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
ubuntu server , vscode IDE, nginx server

* **Angular Seed Version:** `aaaaf75`
c36f6046d57fdc5680206392671b5e09b1f25bd5

* **Node:** `node --version` = v6.9.2

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

Most likely this is rollup configuration issue caused by usage of a commonjs module. Not an issue in the seed.
