### ISSUE TITLE
Child routing example

### ISSUE THREAD

**Issue by ydubey** [mgechev/angular-seed#1832]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
No example with complex child router-outlet.

**Expected behavior**
An example with child routing, lazy loading etc.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
I am quite new to Angular2 and web app dev in general. The seed project has helped me a lot in getting a sample angular2 app working, however I am having trouble setting up a nested child routing page.
A sample page which has child views and uses the same design principals as in the seed project would be a great help.

**Please tell us about your environment:**

Mac, IntelliJ

* **Angular Seed Version:** `aaaaf75`
b93d7b0 

* **Node:** `node --version` =
7.2.1

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

I'd recommend you to take a look at the documentation of Angular to get more complete understanding of a way to go. Another direction you can take is to use Angular CLI which abstracts a lot of things which are let to developers in this seed project. The CLI might be a better starting point since it allows you to treat everything as a black box, compared to Angular Seed which gives you great flexibility but also requires more deep understanding.
