### ISSUE TITLE
Third party CSS build.prod

### ISSUE THREAD

**Issue by ducmaxime** [mgechev/angular-seed#1855]
Hello,

I added some third party css injection in my project.config.ts like this :
   // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
     /* { src: 'lodash/lodash.js', inject: 'libs'},*/
      { src: 'primeng/resources/primeng.css', inject: true },
      { src: 'primeng/resources/themes/omega/theme.css', inject: true },
      { src: 'font-awesome/css/font-awesome.min.css', inject: true },
      { src: '@swimlane/ngx-datatable/release/themes/material.css', inject: true }
    ];

all of css are copied when do build.dev, but not with build.prod.

Any idea ?

**Comment by mgechev** [comment]
I can't reproduce the issue. Maybe wrong paths? All the CSS files gets concatenated into `main.css` which is located in `dist/prod/css`.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
