### ISSUE TITLE
Using APP_BASE breaks after SystemJS update

### ISSUE THREAD

**Issue by Hirse** [mgechev/angular-seed#1952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
After the SystemJS update using APP_BASE breaks when opening the website as SystemJS is trying to load an unprefixed path to `main.js`.
![2017-05-31_15-49-43](https://cloud.githubusercontent.com/assets/2564094/26635082/e3f4c060-4618-11e7-861f-96664fa99f9a.png)

**Expected behavior**
The website opens with the given APP_BASE

**Minimal reproduction of the problem with instructions**

Run `npm start -- --base /hirse/` or `npm start` on https://github.com/Hirse/angular-seed/tree/app-base.

**What is the motivation / use case for changing the behavior?**
I would like to keep using a different APP_BASE.

* **Angular Seed Version:** ` 00c6e8c`

**Comment by mgechev** [comment]
@Hirse thanks for reporting this. I'll try to fix it today.

**Comment by mgechev** [comment]
Yesterday was busier than I expected. Will work on it as soon as possible.

**Comment by brian428** [comment]
I'm not sure if it's related to APP_BASE, but, definitely looks related to the SystemJS version update. After the update, all of my existing import statements (e.g. `import { Observable } from "rxjs";`) no longer work. I end up with console errors like this:

```
SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496361902525:2843:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496361902525:3643:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496361902525:1166:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496361902525:1113:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496361902525:1022:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496361902525:1042:20
    at Object.eval (http://localhost:5555/app/core/services/base-http.service.js:14:14)
    at eval (http://localhost:5555/app/core/services/base-http.service.js:132:4)
    at eval (http://localhost:5555/app/core/services/base-http.service.js:133:3)
```
If I change the import to `import { Observable } from "rxjs/Observable";`, it seems to work. But in reality all it does is move on to the next error. I probably have hundreds of imports like this across the project, so if I really have to change them all, that's going to be quite a pain.

Since I know part of the seed is building its own bundle for RxJS, it _seems_ like it shouldn't be necessary to have change every RxJS import.

If what I'm saying is actually totally unrelated to the APP_BASE issue, let me know and I can create a separate ticket. And finally, if this is actually expected behavior (and maybe I've just been importing from RxJS incorrectly all this time), let me know so I can take the hit and make these changes.

**Comment by dreamindigital** [comment]
I just came here looking for what @brian428 posted. Did a clean install today and everything worked, then I went to import angularfire2 and got this

```
SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496379036118:2843:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496379036118:3643:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496379036118:1166:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496379036118:1113:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496379036118:1022:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496379036118:1042:20
    at Object.eval (http://localhost:5555/app/login/login.component.js:14:18)
    at eval (http://localhost:5555/app/login/login.component.js:71:4)
    at eval (http://localhost:5555/app/login/login.component.js:72:3)
```
Digging through the stack trace I see localhost:5555/angularfire2 being called rather than localhost:5555/node_modules/angularfire2
I had thought `import { Observable } from "rxjs/Observable";` was correct before this.

**Comment by brian428** [comment]
Not sure if it helps or not, but I did some "break on exception" debugging, and the `unexpected token <` is actually because the file that SystemJS is loading is the content of `index.html`. The `<` refers to the opening bracket in the HTML file. So it looks like the SystemJS call to load the JS file(s) is being routed to `index.html` for some reason.

Like I said, not sure if this info helps at all, but I thought I'd mention it.

**Comment by idready** [comment]
@brian428 or anyone else, please is there any workaround or maybe a solution for this?

**Comment by brian428** [comment]
Not on my end yet. Honestly, a lot of the SystemJS config stuff is greek to me. I probably need to invest some time in learning more about it. For now, I'm just holding off on merging the seed updates related to System 0.20.x.

**Comment by idready** [comment]
thanks @brian428 :), i will have to do the same since i'm stuck.

**Comment by brian428** [comment]
I'm sure it's probably some simple SystemJS path/map value that needs to be set, I just don't know enough about it to know what the right config is. I guess that's the danger of using something without really knowing how it works. ;-)

**Comment by mgechev** [comment]
@brian428 you can use `import { Observable } from 'rxjs/Observable';`. We use custom Rx.js bundle in order to speed-up loading which doesn't register the package `rxjs`.

@Hirse, I think the issue is fixed. Let me know if you have any other issues.

**Comment by mgechev** [comment]
Btw, @brian428, you can workaround the issue if you ignore the bundle (so faster initial bootstrap of the build) and load the operators module by module. You'll increase the page reload time.

**Comment by Hirse** [comment]
@mgechev Thanks.
The issue is fixed if I specify the APP_BASE on the command line or change it in the seed config.
However, when I change it in the project config (as it is a permanent setting), it still doesn't work. 
To reproduce, run `npm start` on https://github.com/Hirse/angular-seed/blob/app-base.

**Comment by mgechev** [comment]
Yes, that's a deeper problem that we've discussed a lot in the past but didn't come up with a solution (not that such doesn't exist but we decided that it might not be worth it).

You will also need to overwrite the [`SYSTEM_CONFIG_DEV`](https://github.com/mgechev/angular-seed/blob/master/tools/config/seed.config.ts#L382-L417) (like 407).

**Comment by Hirse** [comment]
Could that be turned into a `get()` so it picks up the updated value?
