### ISSUE TITLE
no-unused-variable tsLint fails on the seed

### ISSUE THREAD

**Issue by oehm-smith** [mgechev/angular-seed#1962]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

We added `no-unused-variable` to our `tslint.json` file.  It failed on ` tools/tasks/seed/copy.prod.rollup.aot.ts`.

Next I forked angular-seed with the plan to fix the problem (it was an unused `const`).

I fixed the `tslint.json` file to reproduce the problem in angular seed.  And ran `npm run lint`.  I received this warning and the lint wasn't run:

    [15:53:04] Starting 'tslint'...
    Warning: The 'no-unused-variable' rule requires type checking
    [15:53:09] Finished 'tslint' after 5.48 s

I'm not sure what this means.  I ran `tslint --type-check --project tsconfig.json` though that turned up a whole lot of errors.

**Expected behavior**

`npm run lint` should run successfully without the warning.

The following line is removed from  `tools/tasks/seed/copy.prod.rollup.aot.ts` so linting passes:

    const replace = require('gulp-replace');

Since replace is no longer used.

I can do this after the linting problem is fixed.

**Minimal reproduction of the problem with instructions**
described above

**What is the motivation / use case for changing the behavior?**
Our builds will fail after we pull in the next version of angular seed.

**Please tell us about your environment:**
Linux, node 7.7.3, npm 4.1.2

* **Angular Seed Version:** `aaaaf75`
Our project's last Seed commit was a26407968cf5b7270e75b6bdfec46bdbe415fa09 (the lint failure for `tools/tasks/seed/copy.prod.rollup.aot.ts`)

But I forked the seed yesterday and the last commit is 0e1c1b579479485af779c68e3033783883457dae (Also has lint failure as that `const replace` is still there and has the `Warning: The 'no-unused-variable' rule requires type checking` linting failing to run issue.)

**Comment by mgechev** [comment]
Most tslint rules provide linting per-file (also called shallow linting). Such rules do not require type checking since they take the content of specific file, build an AST and traverse it afterwards.

On the other hand, other rules require type checking because they perform "deep linting". Since I haven't found necessary to enable type checking for linting (in this case linting takes more time to complete), I haven't added the `--type-checking` flag.

This is not an issue in the seed, shallow linting works as intended. In case you want to allow linting with type checking we can discuss further in this issue and open a PR if we agree that it is needed.
