### ISSUE TITLE
Why is @angular/material excluded from dependencies?

### ISSUE THREAD

**Issue by RoxKilly** [mgechev/angular-seed#1993]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

`package.json` has all the Angular packages with the exception of [Angular Material](https://github.com/angular/material2).

```
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.7",   <--- not found
    "@angular/platform-browser": "^4.2.4",
```

**Expected behavior**

To include all parts of the Angular platform and register all packages with `SystemJS`, but let the user import what she needs in her app. I figured maybe Material is excluded because it's still in beta, but I notice that `@angular/service-worker` is included

**What is the motivation / use case for changing the behavior?**

To be consistent

**Comment by vyakymenko** [comment]
Hi @RoxKilly , I think that main idea of the seed is a working project skeleton.

For my understanding `@angular/service-worker` is included because it has ServiceWorker support from the box, and you need just uncomment few lines of code to see how your project works in offline, more detailed:
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

About `@angular/material`, it's a UI Framework that may not be included by default, because one user wants to use `PrimeNG` framework, etc.

So if `@angular/material` will be included by default, developers will be very confused. Depend on their architecture and structure, most of the developers that are not using `@angular/material` will lose the possibility to do fast core updates from upstream of this seed, because they will always remove `@angular/material` framework each update... I don't think that this is a good idea.

Conclusion:
The current structure is very good at this point and we don't need to include by default any UI frameworks.

**Comment by RoxKilly** [comment]
thanks for the detailed response
